### ISSUE TITLE
Update the Project Description to use a RTE instead of a string

### ISSUE THREAD

**Issue by absempere** [AVAnnotate/admin-client#140]
As a scholar, I would like my auto-generated homepage to show paragraph breaks and formatted text including italicized, bold, or underlined text and links. I would like to include citations and references in my description.

**Comment by camdendotlol** [comment]
I know this isn't in my queue yet but I just noticed it and wanted to mention: this would be pretty hard unless we're willing to break old projects. Since AVAnnotate isn't a traditional website with a database, we can't run any sort of database migration to change data types. Existing projects would still have string descriptions after deploying a rich text update, so both the project client and admin client would need to be updated to support both types to avoid crashes.

**Comment by absempere** [comment]
@camdendotlol This was on a list of "would be nice if we have time" but we don't have time, and I think the custom home page + ToC addresses the issue already.
